version: "3.4"

services:
  php:
    build:
      context: ./api
      target: app_php
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/redis-data
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '8081:8025'

volumes:
  php_socket:
  redis: