parameters:

imports:
    - { resource: '../src/Module/Notifications/Infrastructure/Resources/services.yaml'}
    - { resource: '../src/Module/Messages/Infrastructure/Resources/services.yaml'}
    - { resource: '../src/Module/ExampleClient/Infrastructure/Resources/services.yaml'}

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Framework\:
        resource: '../src/Module/Framework/**'
        exclude: '../src/Module/Framework/Kernel.php'