services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Notifications\:
    resource: '../../**'
    exclude: '../../{Tests,Infrastructure}'

  #Notificator
  Notifications\Domain\NotificatorInterface:
    class: Notifications\Domain\Notificator
    arguments:
      - !tagged_iterator notification_channels.channel

  Notifications\Domain\LoggableNotificator:
    decorates: Notifications\Domain\NotificatorInterface
    arguments:
      - '@.inner'

  #Notification channels (from first injected to last)
  Notifications\Domain\Channels\EmailChannel:
    arguments:
      - !tagged_iterator notification_channels_providers.email_transport
    tags:
      - { name: 'notification_channels.channel', priority: 10 }

  Notifications\Domain\Channels\PhoneChannel:
    arguments:
      - !tagged_iterator notification_channels_providers.sms_transport
    tags:
      - { name: 'notification_channels.channel', priority: 5 }

  #Notification transports
  Notifications\Infrastructure\Adapter\AwsSesTransport:
    tags:
      - { name: 'notification_channels_providers.email_transport', priority: 10 }

  Notifications\Infrastructure\Adapter\TwilioSmsTransport:
    tags:
      - { name: 'notification_channels_providers.sms_transport', priority: 10 }

  aws_ses_email_transport_ganesha_decorator:
    class: Notifications\Infrastructure\Adapter\GaneshaTransportDecorator
    decorates: Notifications\Infrastructure\Adapter\AwsSesTransport
    arguments:
      - '@.inner'
      - '@Ackintosh\Ganesha'

  twilio_sms_transport_ganesha_decorator:
    class: Notifications\Infrastructure\Adapter\GaneshaTransportDecorator
    decorates: Notifications\Infrastructure\Adapter\TwilioSmsTransport
    arguments:
      - '@.inner'
      - '@Ackintosh\Ganesha'

  Notifications\Application\Port\MessagesPort:
    class: Notifications\Infrastructure\Adapter\MessagesAdapter
    arguments:
      - '@Messages\Domain\Messages'

  Notifications\Domain\Channels\ChannelsFeatureFlags:
    class: Notifications\Infrastructure\Adapter\InMemoryChannelsFeatureFlags

  Notifications\Domain\NotificationsLogs:
    class: Notifications\Infrastructure\Adapter\MonologNotificationsLogs
    arguments:
      - '@monolog.logger.notifications_logs'

  #Ganesha circuit breaker
  Notifications\Infrastructure\Factory\GaneshaFactory:
    arguments:
      - '@notifications_ganesha_redis_client'
      - '@monolog.logger.circuit_breaker_logs'

  Ackintosh\Ganesha:
    factory: [ '@Notifications\Infrastructure\Factory\GaneshaFactory', 'build' ]

  #Redis
  notifications_ganesha_redis_client:
    class: Predis\Client
    arguments:
      $parameters: "%env(REDIS_URI)%"
      $options:
        prefix: 'notifications_ganesha:'
        read_write_timeout: 0